site_name: Modular Orchestrated Core
site_description: Arquitectura modular orientada a plugins y orquestadores por cliente
site_author: Tu Nombre
site_url: https://<tu-usuario>.github.io/<nombre-del-repo>/

theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: blue

nav:
  - Inicio: index.md
  - Contexto:
      - Antecedentes: content/1.context/background.md
  - Método:
      - Componentes:
          - Núcleo (Core): content/2.method/components/core.md
          - Plugins: content/2.method/components/plugins.md
          - Orchestrators: content/2.method/components/orchestrators.md
          - Tenants: content/2.method/components/tenants.md
  - Implementación:
      - Buenas prácticas: content/3.implementation/buenas-practicas.md
      - Casos de uso: content/3.implementation/casos-de-uso.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji

# Carpeta con los archivos Markdown
docs_dir: content

# Ignora carpeta site al hacer seguimiento en git
exclude:
  - site

# Despliegue automático a GitHub Pages
# Ejecuta esto para publicar: mkdocs gh-deploy
