site_name: Modular Orchestrated Core
site_description: Arquitectura modular orientada a plugins y orquestadores por cliente
site_author: Jeisson Rodríguez
site_url: https://jeissonr115.github.io/modular_orchestrated_core/

theme:
  name: material
  locale: co
  language: es

plugins:
  - gen-files
  - literate-nav

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
