import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "index", // docs/index.md
      label: "Inicio",
    },
    {
      type: "doc",
      id: "context", // docs/context.md
      label: "Contexto",
    },
    {
      type: "category",
      link: {
        type: "doc",
        id: "architecture/index",
      },
      label: "Arquitectura",
      items: [
        {
          type: "doc",
          id: "architecture/advantages-disadvantages",
          label: "Ventajas y Desventajas",
        },
        {
          type: "category",
          label: "Componentes",
          items: [
            {
              type: "autogenerated",
              dirName: "architecture/components",
            },
          ],
        },
        {
          type: "doc",
          id: "architecture/relationship",
          label: "Relaciones",
        },
        {
          type: "doc",
          id: "architecture/responsibilities",
          label: "Responsabilidades",
        },
      ],
    },
    {
      type: "category",
      label: "Implementación",
      items: [{ type: "autogenerated", dirName: "implementation" }],
    },
  ],
};

export default sidebars;
